laurel_sprout: added missing `set` method to BiometricsFingerprint
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:430:5: error: use of undeclared identifier 'set'
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_ON);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:432:5: error: use of undeclared identifier 'set'
    set(FOD_STATUS_PATH, FOD_STATUS_ON);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:439:5: error: use of undeclared identifier 'set'
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_OFF);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:441:5: error: use of undeclared identifier 'set'
    set(FOD_STATUS_PATH, FOD_STATUS_OFF);